# Generated by Django 4.2.1 on 2023-06-23 20:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('FotoAqui', '0002_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='order',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='FotoAqui.order'),
        ),
    ]
