# Generated by Django 4.2.1 on 2023-06-26 02:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FotoAqui', '0004_alter_business_model_img_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='business_model',
            name='active',
            field=models.BooleanField(default=False),
        ),
    ]
