# Generated by Django 4.2.1 on 2023-06-26 02:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FotoAqui', '0005_business_model_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='qtd_imgs',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
