# Generated by Django 4.2.1 on 2023-07-01 15:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('FotoAqui', '0008_business_model_expiration_time_image_expiration_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='dislike',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='image',
            name='like',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='order',
            name='account',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, to=settings.AUTH_USER_MODEL),
        ),
    ]
