# Generated by Django 4.2.1 on 2023-07-04 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FotoAqui', '0009_image_dislike_image_like_alter_order_account'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='img_perfil',
            field=models.ImageField(default='static/layout/perfilDefault.png', upload_to='imgs/perfis/%Y'),
        ),
    ]
