# Generated by Django 4.2.1 on 2023-07-04 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FotoAqui', '0010_alter_account_img_perfil'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='img_perfil',
            field=models.ImageField(default='../static/perfilDefault.png', upload_to='imgs/perfis/%Y'),
        ),
    ]
