# Generated by Django 4.2.1 on 2023-09-07 02:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('FotoAqui', '0012_alter_account_img_perfil'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='img_perfil',
            field=models.ImageField(default='SEM-IMAGEM', upload_to='imgs/perfis/%Y'),
        ),
        migrations.CreateModel(
            name='Wallet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.FloatField(default=0.0)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Operation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('op_type', models.CharField(default='deposito', max_length=12)),
                ('value', models.FloatField(default=0.0)),
                ('data', models.DateTimeField(auto_now_add=True)),
                ('wallet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='FotoAqui.wallet')),
            ],
        ),
    ]
