# Generated by Django 4.2.1 on 2023-09-07 13:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('FotoAqui', '0013_alter_account_img_perfil_wallet_operation'),
    ]

    operations = [
        migrations.AddField(
            model_name='operation',
            name='order',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='FotoAqui.order'),
        ),
    ]
