# Generated by Django 4.2.1 on 2023-09-14 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FotoAqui', '0014_operation_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='likes',
            field=models.IntegerField(default=0),
        ),
    ]
